// Auto-generated by build.js — non modificare manualmente
// Playlist: PLtR9p5sG4XcPvvaq-LWk0Mqo7JUVonqFT  |  Last updated: 2026-06-24
const YOUTUBE_PLAYLIST = {
  "playlistId": "PLtR9p5sG4XcPvvaq-LWk0Mqo7JUVonqFT",
  "videos": [
    { "id": "KOE4X3H9oIg", "title": "Why not - stop motion - lasagne" },
    { "id": "FMxNmCeFscQ", "title": "Why not - stop motion - passatelli" },
    { "id": "1oy76vNCWU0", "title": "Why not - stop motion - vin santo" },
    { "id": "CBjemldidRw", "title": "Why not - stop motion - ragù" },
    { "id": "Min-w6b6SSI", "title": "pony - progetto whynot",       "thumb": "assets/images/video-thumbs/pony.png" },
    { "id": "HnBhipZDnTw", "title": "pavone - progetto whynot",     "thumb": "assets/images/video-thumbs/pavone.png" },
    { "id": "gyINxdWeUMo", "title": "pecora - progetto whynot",     "thumb": "assets/images/video-thumbs/pecora.png" },
    { "id": "uRLDMC_cGFQ", "title": "capra - progetto whynot",      "thumb": "assets/images/video-thumbs/capra.png" },
    { "id": "pgdx2e5VCA8", "title": "gatto - progetto whynot",      "thumb": "assets/images/video-thumbs/gatto.png" },
    { "id": "we7cCWoREdk", "title": "maiale - progetto whynot",     "thumb": "assets/images/video-thumbs/maiale.png" },
    { "id": "CV8RhnKZiu4", "title": "asino sardo - progetto whynot","thumb": "assets/images/video-thumbs/asino.png" },
    { "id": "AA_rXva_nfc", "title": "alpaca - progetto whynot",     "thumb": "assets/images/video-thumbs/alpaca.png" },
    { "id": "0v3GMgX0TtY", "title": "pappagallo - progetto whynot", "thumb": "assets/images/video-thumbs/pappagallo.png" },
    { "id": "2-HV3dENSr8", "title": "coniglio - progetto whynot",   "thumb": "assets/images/video-thumbs/coniglio.png" },
    { "id": "BXy2Ym3Sdyk", "title": "gallo - progetto whynot",      "thumb": "assets/images/video-thumbs/gallo.png" },
    { "id": "MHOaWFZ6_AI", "title": "cane - progetto whynot",       "thumb": "assets/images/video-thumbs/cane.png" }
  ]
};
