// Auto-generated by build.js — non modificare manualmente
// Playlist: PLtR9p5sG4XcPvvaq-LWk0Mqo7JUVonqFT  |  Last updated: 2026-04-10T13:31:26.944Z
const YOUTUBE_PLAYLIST = {
  "playlistId": "PLtR9p5sG4XcPvvaq-LWk0Mqo7JUVonqFT",
  "videos": [
    {
      "id": "KOE4X3H9oIg",
      "title": "Why not - stop motion - lasagne"
    },
    {
      "id": "FMxNmCeFscQ",
      "title": "Why not - stop motion - passatelli"
    },
    {
      "id": "1oy76vNCWU0",
      "title": "Why not - stop motion - vin santo"
    },
    {
      "id": "CBjemldidRw",
      "title": "Why not - stop motion - ragù"
    }
  ]
};
