// build.js — genera js/version.js e js/playlist-data.js prima del deploy su Vercel

const { execSync } = require('child_process');
const fs = require('fs');
const https = require('https');

// ── Version ─────────────────────────────────────────────────────────────────
let version = '0.1';
try {
  const count = execSync('git rev-list --count HEAD', { encoding: 'utf8' }).trim();
  version = `0.${count}`;
} catch (e) {
  const pkg = require('./package.json');
  version = pkg.version;
}

const content = `// Auto-generated by build.js — non modificare manualmente\nconst APP_VERSION = '${version}';\n`;
fs.writeFileSync('js/version.js', content);
console.log(`✓ Version set to ${version}`);

// ── YouTube Playlist data ────────────────────────────────────────────────────
const PLAYLIST_ID = 'PLtR9p5sG4XcPvvaq-LWk0Mqo7JUVonqFT';

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'Mozilla/5.0' } }, res => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => resolve(data));
    }).on('error', reject);
  });
}

async function fetchPlaylist() {
  try {
    const xml = await fetchText(
      `https://www.youtube.com/feeds/videos.xml?playlist_id=${PLAYLIST_ID}`
    );
    const ids    = [...xml.matchAll(/<yt:videoId>([^<]+)<\/yt:videoId>/g)].map(m => m[1]);
    const titles = [...xml.matchAll(/<title>([^<]+)<\/title>/g)].map(m => m[1]).slice(1);
    const videos = ids.map((id, i) => ({ id, title: titles[i] || '' }));

    const js = `// Auto-generated by build.js — non modificare manualmente
// Playlist: ${PLAYLIST_ID}  |  Last updated: ${new Date().toISOString()}
const YOUTUBE_PLAYLIST = ${JSON.stringify({ playlistId: PLAYLIST_ID, videos }, null, 2)};
`;
    fs.writeFileSync('js/playlist-data.js', js);
    console.log(`✓ Playlist fetched: ${videos.length} video/i`);
  } catch (e) {
    console.warn('⚠ Playlist fetch failed, keeping existing file:', e.message);
    // Don't overwrite existing file if fetch fails
    if (!fs.existsSync('js/playlist-data.js')) {
      fs.writeFileSync('js/playlist-data.js',
        `// Auto-generated by build.js\nconst YOUTUBE_PLAYLIST = { playlistId: '${PLAYLIST_ID}', videos: [] };\n`
      );
    }
  }
}

fetchPlaylist();
