// build.js — genera js/version.js prima del deploy su Vercel
// La versione è 0.N dove N = numero di commit git (auto-incrementale)

const { execSync } = require('child_process');
const fs = require('fs');

let version = '0.1';
try {
  const count = execSync('git rev-list --count HEAD', { encoding: 'utf8' }).trim();
  version = `0.${count}`;
} catch (e) {
  // fallback se git non disponibile (es. build senza history)
  const pkg = require('./package.json');
  version = pkg.version;
}

const content = `// Auto-generated by build.js — non modificare manualmente\nconst APP_VERSION = '${version}';\n`;
fs.writeFileSync('js/version.js', content);
console.log(`✓ Version set to ${version}`);
